config/routes.rb
Rails.application.routes.draw do
  get '/user_management', to: 'user_management#index', as: 'user_management'
  resources :sellers do
    member do
      post 'associate_seller', to: 'devices#associate_seller'
      
      delete 'destroy_sellers', to: 'sellers#destroy_sellers'
      #delete 'dissociate_seller', to: 'devices#dissociate_seller'
      delete 'dissociate_seller/:device_id', to: 'sellers#dissociate_seller', as: :dissociate_seller
    end
    get 'attach_devices'
    post 'save_attached_devices'
  end

  get 'home/index'
  get 'esp8266/index'
  root 'home#index'
  get '/status', to: 'status#index'
  resources :devicelogs, only: [:index]
  get 'associar_dispositivo_usuario', to: 'devices#associar_dispositivo_usuario'
  delete 'devices/:id/dissociate', to: 'devices#dissociate', as: 'dissociate_device'
  get '/devices/in_use', to: 'devices#in_use', as: 'devices_in_use'
  get '/devices/in_use_seller', to: 'devices#in_use_seller', as: 'devices_in_use_seller'
  get '/user/dashboard', to: 'user#dashboard', as: 'dashboard'
  get '/user/managerseller', to: 'sellers#managerseller', as: 'managerseller'
  get '/user/userdevice', to: 'devices#userdevice', as: 'userdevice'


  

  



  resources :dose_prices

  namespace :administrador do
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  
  resources :devices do
    post 'associate_device_seller'
    post 'assign_device', on: :member
    post 'save_to_database', on: :collection
    post 'save_data', on: :collection
    post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  end

  post 'devices/associate', to: 'devices#associate', as: 'associate_device'
  post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  resources :devices, only: [:new, :create, :show, :destroy]
  

  devise_for :users
  #devise_for :users, controllers: { registrations: 'users/registrations' }


  resources :admin, only: [:destroy]
  resources :users, only: [:index, :show, :destroy]
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      #delete '/users/cancel', to: 'users/registrations#destroy', as: :cancel_user_registration
    end


  # Rotas para o Admin
  get 'admin/index', as: 'admin_index'

  # Rotas para o User
  get 'user/index', as: 'user_index'

  # Rotas para o Envio de SMS
  

  resources :sms_messages 
    post '/send_sms_twilio', to: 'sms_messages#send_sms_twilio'
    # Rotas para o Envio de Whatsapp
    post '/send_whatsapp_message_twilio', to: 'sms_messages#send_whatsapp_message_twilio'
    get '/logs_message', to: 'sms_messages#logs_message'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/sms_message.rb
class SmsMessage < ApplicationRecord
end

app/controllers/sms_messages_controller.rb
require 'httparty'
require 'twilio-ruby'

class SmsMessagesController < ApplicationController
  before_action :set_sms_message, only: %i[ show edit update destroy ]

  # GET /sms_messages or /sms_messages.json
  def index
    #@sms_messages = SmsMessage.all
    @sms_logs = SmsLog.all
    @sms_messages = SmsMessage.all
    @last_sms_message = @sms_messages.last
    #@sms_messages = SmsMessage.last
  end

  # GET /sms_messages/1 or /sms_messages/1.json
  def show
  end

  # GET /sms_messages/new
  def new
    @sms_message = SmsMessage.new
    #@sms_template = SmsTemplate.new
  end

  # GET /sms_messages/1/edit
  def edit
    #@sms_message = SmsMessage.find(params[:id])
  end


  # POST /sms_messages or /sms_messages.json
  def create
    @sms_message = SmsMessage.new(sms_message_params)

    respond_to do |format|
      if @sms_message.save
        format.html { redirect_to sms_messages_path(@sms_message), notice: "Sms message was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sms_messages/1 or /sms_messages/1.json
  def update
    respond_to do |format|
      if @sms_message.update(sms_message_params)
        format.html { redirect_to sms_messages_path(@sms_message), notice: "Sms message was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def logs_message
    @sms_logs = SmsLog.all
  end

  # DELETE /sms_messages/1 or /sms_messages/1.json
  def destroy
    @sms_message.destroy

    respond_to do |format|
      format.html { redirect_to sms_messages_url, notice: "Sms message was successfully destroyed." }
    end
  end

  def send_sms_twilio
    account_sid = 'ACcbd199f02e7c1e843cd953a16ac1e714'
    auth_token = '81ad8e628f8487a68a5d3b2131e149f9'
    client = Twilio::REST::Client.new(account_sid, auth_token)

    phone_numbers = fetch_phone_numbers_from_api
    if params[:cont].to_i == 80 && phone_numbers.any?
      phone_number = phone_numbers.first['phone']
      send_sms_to_phone(client, phone_number)
      #redirect_to sms_messages_path, notice: "SMS enviado automaticamente!"
      return
    else
      render json: { message: 'SMS nao enviado automaticamente.' }
      return
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sms_message
      @sms_message = SmsMessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sms_message_params
      params.require(:sms_message).permit(:smsbody)
    end

    def fetch_phone_numbers_from_api
      api_url = 'https://dispenser-smart-api-9ae096adb72b.herokuapp.com/esp8266s'
      headers = {
        'Authorization' => 'Bearer YOUR_API_TOKEN' # Se sua API necessita de um token de autenticação, adicione-o aqui
      }
      
      response = HTTParty.get(api_url, headers: headers)
      if response.success?
        response.parsed_response
      else
        []
      end
    end

    def send_sms_to_phone(client, phone_number)
      from = '15416128239' # Número de telefone fornecido pela Twilio
      puts "Conteúdo de @last_sms_message: #{@last_sms_message}"
      body = @last_sms_message = SmsMessage.last
      #body = @last_sms_message.smsbody # Corpo da mensagem SMS
      #body = "TESTE" # Corpo da mensagem SMS

      
      #to = '5561992488131' # Número de telefone do destinatário Luis RFID
      #to = '5561998058131'
      #to = '5561995762787' # Número de telefone do destinatário Caio
      #to = '5561993212899' #Caian
      #to = '5561991150833' #Ivanice
  
      message = client.messages.create(
        from: from,
        to: phone_number,
        body: body
      )
  
      # Salva o log da mensagem
      sms_log = SmsLog.create(
        from_number: message.from,
        to_number: message.to,
        body: message.body,
        sent_at: Time.now
      )
    rescue Twilio::REST::TwilioError => e
      render json: { error: e.message }, status: :unprocessable_entity
    end
end

app/helpers/sms_messages_helper.rb
module SmsMessagesHelper
end

app/views/sms_messages/_form.html.erb
<%= form_with(model: sms_message) do |form| %>
  <% if sms_message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sms_message.errors.count, "error") %> prohibited this sms_message from being saved:</h2>

      <ul>
        <% sms_message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :smsbody, style: "display: block" %>
    <%= form.text_field :smsbody %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sms_messages/_sms_message.html.erb
<div id="<%= dom_id sms_message %>">
  <p>
    <strong>Smsbody:</strong>
    <%= sms_message.smsbody %>
  </p>

</div>

app/views/sms_messages/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Editar Mensagem Padrão</h1>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->
            <div class="col-lg-9">
              <%= form_for @sms_message do |f| %>
                <%= f.label :smsbody, "Mensagem:" %>
                <%= f.text_area :smsbody, class: "form-control" %>
                </br>
                <%= f.submit "Atualizar", class: "btn btn-primary" %>
                <%= link_to "Voltar", sms_messages_path, class: "btn btn-success" %>
              <% end %>
            </div> 
          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>

app/views/sms_messages/index.html.erb
<div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Configurações de Alerta</h1>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->

            <div class="container">
              <div class="row justify-content-center">
                <div class="col-lg-9">
                  <div class="container">
                    <!-- Exibe o formulário de criação ou edição da mensagem padrão -->
                    <% if @sms_messages.any? %>
                      <% last_sms_message = @sms_messages.last %>
                      <h2>Mensagem Padrão: <%= last_sms_message.smsbody %></h2>
                      <br>
                      <div class="d-flex justify-content-center flex-wrap">
                        <%= form_tag send_sms_twilio_path, method: :post, class: "d-inline" do %>
                          <%= hidden_field_tag :phone, '5561995762787' %> <!-- Número de telefone para disparo -->
                          <%= hidden_field_tag :cont, '80' %> <!-- Exemplo do campo "cont" igual a 80 -->
                          <%= submit_tag "Disparar SMS", class: "btn btn-success mt-2 me-2" %>
                        <% end %>
                        
                        <%= link_to "Editar", edit_sms_message_path(last_sms_message), class: "btn btn-primary mt-2 me-2" %>
                        <%= link_to "Histórico de Alertas", logs_message_path, class: "btn btn-warning mt-2 me-2" %>
                        <%= button_to "Apagar", sms_message_path(last_sms_message), method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-danger mt-2 me-2" %>
                      </div>
                    <% else %>
                      <p class="mt-4">Nenhuma mensagem padrão criada.</p>
                      <%= link_to "Criar Mensagem Padrão", new_sms_message_path, class: "btn btn-primary mt-2" %>
                    <% end %>
                    <!-- Botão de disparo manual do SMS -->
                  </div>
                </div>
              </div>
            </div>


          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>

app/views/sms_messages/logs_message.html.erb
<div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Histórico de Mensagem</h1>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->
            <div class="container">
              <div class="d-flex justify-content-center">
                <table class="table table-responsive-sm">
                  <thead>
                    <tr>
                      <th>De</th>
                      <th>Para</th>
                      <th>Mensagem</th>
                      <th>enviado em</th>
                    </tr>
                  </thead>
                    <tbody>
                        <% @sms_logs.each_with_index do |sms_log, index| %>
                          <tr>
                            <td class="text-center"><%= sms_log.from_number %></td>
                            <td class="text-center"><%= sms_log.to_number %></td>
                            <td class="text-center"><%= sms_log.body %></td>
                            <td class="text-center"><%= sms_log.sent_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
                            </tr>
                          <% end %>
                    </tbody>
                </table>
              </div>
            </div>
          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>

app/views/sms_messages/new.html.erb
<div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Nova Mensagem</h1>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->
            <div class="row">
              <div class="col-md-12 col-sm-12">
                <div class="dashboard_graph">
                  <div class="row x_title">
                    <div class="col-md-6">
                    </div>
                  </div>
                  <%= form_for @sms_message do |f| %>
                    <div class="form-group">
                      <%= f.label :smsbody, "Mensagem:" %>
                      <%= f.text_area :smsbody, class: "form-control" %>
                    </div>
          
                    <div class="form-group">
                      <%= f.submit "Salvar", class: "btn btn-primary" %>
                    </div>
                  <% end %>
                  <!-- /top tiles -->
                  <!-- /FInal Tabela -->
                </div>
              </div>
            </div>

          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>

app/views/sms_messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sms_message %>

<div>
  <%= link_to "Edit this sms message", edit_sms_message_path(@sms_message) %> |
  <%= link_to "Back to sms messages", sms_messages_path %>

  <%= button_to "Destroy this sms message", @sms_message, method: :delete %>
</div>