config/routes.rb
Rails.application.routes.draw do
  get '/user_management', to: 'user_management#index', as: 'user_management'
  resources :sellers do
    member do
      post 'associate_seller', to: 'devices#associate_seller'
      
      delete 'destroy_sellers', to: 'sellers#destroy_sellers'
      #delete 'dissociate_seller', to: 'devices#dissociate_seller'
      delete 'dissociate_seller/:device_id', to: 'sellers#dissociate_seller', as: :dissociate_seller
    end
    get 'attach_devices'
    post 'save_attached_devices'
  end

  get 'home/index'
  get 'esp8266/index'
  root 'home#index'
  get '/status', to: 'status#index'
  resources :devicelogs, only: [:index]
  get 'associar_dispositivo_usuario', to: 'devices#associar_dispositivo_usuario'
  delete 'devices/:id/dissociate', to: 'devices#dissociate', as: 'dissociate_device'
  get '/devices/in_use', to: 'devices#in_use', as: 'devices_in_use'
  get '/devices/in_use_seller', to: 'devices#in_use_seller', as: 'devices_in_use_seller'
  get '/user/dashboard', to: 'user#dashboard', as: 'dashboard'
  get '/user/managerseller', to: 'sellers#managerseller', as: 'managerseller'
  get '/user/userdevice', to: 'devices#userdevice', as: 'userdevice'


  

  



  resources :dose_prices

  namespace :administrador do
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  
  resources :devices do
    post 'associate_device_seller'
    post 'assign_device', on: :member
    post 'save_to_database', on: :collection
    post 'save_data', on: :collection
    post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  end

  post 'devices/associate', to: 'devices#associate', as: 'associate_device'
  post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  resources :devices, only: [:new, :create, :show, :destroy]
  

  devise_for :users
  #devise_for :users, controllers: { registrations: 'users/registrations' }


  resources :admin, only: [:destroy]
  resources :users, only: [:index, :show, :destroy]
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      #delete '/users/cancel', to: 'users/registrations#destroy', as: :cancel_user_registration
    end


  # Rotas para o Admin
  get 'admin/index', as: 'admin_index'

  # Rotas para o User
  get 'user/index', as: 'user_index'

  # Rotas para o Envio de SMS
  

  resources :sms_messages 
    post '/send_sms_twilio', to: 'sms_messages#send_sms_twilio'
    # Rotas para o Envio de Whatsapp
    post '/send_whatsapp_message_twilio', to: 'sms_messages#send_whatsapp_message_twilio'
    get '/logs_message', to: 'sms_messages#logs_message'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/seller.rb
class Seller < ApplicationRecord
    #has_and_belongs_to_many :devices #funciona basta voltar
    has_many :device_sellers
    has_many :devices, through: :device_sellers
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :authenticate_user! # Certifique-se de que o usuário esteja autenticado
  before_action :set_seller, only: %i[show edit update destroy attach_devices save_attached_devices]

  # GET /sellers or /sellers.json
  def index
    @sellers = Seller.all
    @devices = Device.all
    #@devices = Device.includes(:seller)
  end

  def managerseller
    #@sellers = Seller.where(creator_id: current_user.id)
    @sellers = current_user.sellers # Obtém todos os vendedores do usuário atual
  end


  def dissociate_seller
    @seller = Seller.find(params[:seller_id])
    @device = Device.find(params[:device_id])

    if @device.sellers.exists?(@seller)
      @device.sellers.delete(@seller)
      flash[:success] = 'Vendedor desassociado com sucesso.'
    else
      flash[:error] = 'Vendedor não está associado a este dispositivo.'
    end

    redirect_to devices_path
  end

  def associate_device_seller
    @device = Device.find(params[:id])
    seller_id = params[:device][:seller_id]
    @seller = Seller.find(seller_id)

    if @device.update(seller_id: seller_id)
      redirect_to @device, notice: "Device associated with seller successfully!"
    else
      render :show, alert: "Error associating the device with the seller."
    end
  end


  def attach_devices
    @seller = Seller.find(params[:id])
    @devices = Device.all
  end

  def save_attached_devices
    @seller = Seller.find(params[:id])
    selected_device_ids = params[:seller][:device_ids]

    # Limpa as associações atuais com os devices
    @seller.devices.clear

    # Associa os dispositivos selecionados ao seller
    if selected_device_ids.present?
      selected_device_ids.each do |device_id|
        device = Device.find(device_id)
        @seller.devices << device
      end
    end

    redirect_to sellers_path, notice: 'Devices atrelados com sucesso!'
  end

  # GET /sellers/1 or /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers or /sellers.json
  def create
    @seller = current_user.sellers.build(seller_params)
    #@seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to seller_url(@seller), notice: "Seller was successfully created." }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1 or /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to seller_url(@seller), notice: "Seller was successfully updated." }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1 or /sellers/1.json
  def destroy
    if @seller.device_sellers.any?
      # Se o vendedor estiver associado a dispositivos, você pode decidir o que fazer,
      # como desassociar o vendedor desses dispositivos ou simplesmente impedir a exclusão.
      flash[:alert] = "Não é possível excluir este vendedor porque ele está associado a dispositivos."
      redirect_to sellers_url
    else
      @seller.destroy
      respond_to do |format|
        format.html { redirect_to sellers_url, notice: "Seller was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  def destroy_sellers
      # Ação para destruir um recurso (por exemplo, um vendedor)
    @seller = Seller.find(params[:id])
    @seller.destroy
    
    redirect_to sellers_path, notice: 'Vendedor destruído com sucesso.' # Redireciona para a página de índice ou outra rota apropriada.
  end

  def associate_device
    @seller = Seller.find(params[:seller_id])
    @device = Device.find(params[:device_id])

    if @device.sellers << @seller
      redirect_to devices_path, notice: 'Vendedor associado com sucesso!'
    else
      redirect_to devices_path, alert: 'Erro ao associar vendedor ao dispositivo.'
    end
  end

  private

    # Define o filtro para carregar o @seller com base no ID fornecido na URL
    def set_seller
      @seller = Seller.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to sellers_path, alert: 'Seller não encontrado.'
    end


    # Only allow a list of trusted parameters through.
    def seller_params
      params.require(:seller).permit(:id, :status, :nome, :cardRFID, :cargo, :contador, :email)
    end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: seller, class: "form") do |form| %>
        <% if seller.errors.any? %>
          <div class="alert alert-danger">
            <h2><%= pluralize(seller.errors.count, "error") %> prohibited this seller from being saved:</h2>
            <ul>
              <% seller.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :status %>
          <%= form.select :status, [['Ativo', 'Ativo'], ['Inativo', 'Inativo']], { include_blank: true }, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :nome %>
          <%= form.text_field :nome, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :cargo %>
          <%= form.text_field :cargo, class: "form-control" %>
        </div>

        <div class="d-flex justify-content-between">
          <div class="form-group">
            <%= form.submit "Salvar Vendedor", class: "btn btn-primary" %>
          </div>
          <div class="form-group">
            <%= link_to "Voltar", sellers_path, class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sellers/_seller.html.erb
<div id="<%= dom_id seller %>">
  <p>
    <strong>Status:</strong>
    <%= seller.status %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= seller.nome %>
  </p>

  <p>
    <strong>Cardrfid:</strong>
    <%= seller.cardRFID %>
  </p>

  <p>
    <strong>Cargo:</strong>
    <%= seller.cargo %>
  </p>

  <p>
    <strong>Contador:</strong>
    <%= seller.contador %>
  </p>

  <p>
  <strong>Email:</strong>
  <%= seller.email %>
</p>

</div>

app/views/sellers/attach_devices.html.erb
><div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Bem-vindo ao Painel Administrativo</h1>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->
            <!-- app/views/sellers/attach_devices.html.erb -->
              <h1>Atrelar Devices ao Seller</h1>
              <%= form_with model: @seller, url: save_attached_devices_seller_path(@seller), method: :post do |f| %>
                <h2>Dispositivos Disponíveis</h2>
                <% @devices.each do |device| %>
                  <%= check_box_tag "seller[device_ids][]", device.id, @seller.devices.include?(device) %>
                  <%= device.nome %>
                  <br>
                <% end %>
                <%= f.submit "Salvar" %>
              <% end %>
          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>

app/views/sellers/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Bem-vindo ao Painel Administrativo</h1>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-md-8">
                  <%= render "form", seller: @seller %>
                </div>
              </div>
            </div>
            

          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>

app/views/sellers/index.html.erb
<div class="container-fluid">
    <div class="row">
      <!-------------------- --Conteúdo principal ------------------------->
      <!-- Conteúdo principal -->
        <div class="col-lg-9">
          <h1 class="mt-4">Gerenciamento de Vendedores</h1>
            <% if current_user.admin? %>
              <%= link_to devices_in_use_seller_path, class: 'btn btn-success' do %>
                <i class="fa fa-plus"></i> Atrelar Vendedor ao Dispositivo
              <% end %>
              <% else %>
                <div class="d-flex">
                  <%= link_to new_seller_path, class: "btn btn-success me-2" do %>
                    <i class="fa fa-user-plus"></i> Novo vendedor
                  <% end %>
                
                  <%= link_to devices_in_use_seller_path, class: 'btn btn-success' do %>
                    <i class="fa fa-plus"></i> Atrelar Vendedor ao Dispositivo
                  <% end %>
                </div>
            <% end %>
          <div class="right_col" role="main">
            <!-- ... (conteúdo do gráfico e da tabela) ... -->
              <div class="container">
                <div class="row justify-content-center">
                  <div class="col-md-12">
                    <div class="table-responsive">
                      <table class="table table-responsive-sm">
                        <thead>
                          <tr>
                            <th>Status</th>
                            <th>Nome</th>
                            <th>Cartão RFID</th>
                            <th>Cargo</th>
                            <th>Doses</th>
                            <th>Email</th>
                            <th>Ver</th>
                            <th>Editar</th>
                            <th>Excluir</th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @sellers.each do |seller| %>
                            <tr>
                              <td><%= seller.status %></td>
                              <td><%= seller.nome %></td>
                              <td><%= seller.cardRFID %></td>
                              <td><button type="button" class="btn btn-info"><%= seller.cargo %></button></td>
                              <td><%= seller.contador %></td>
                              <td><%= seller.email %></td>
                              <td>
                                <%= button_to seller_path(seller), method: :get, class: 'btn btn-primary' do %>
                                  <i class="fa fa-search"></i>
                                <% end %>
                              </td>
              
                              <td>
                                <%= button_to edit_seller_path(seller), method: :get, class: 'btn btn-warning' do %>
                                  <i class="fa fa-edit"></i>
                                <% end %>
                              </td>
              
                              <td>
                                <%= button_to seller_path(seller), method: :delete, data: { confirm: 'Tem certeza que deseja excluir este usuário?' }, class: 'btn btn-danger' do %>
                                  <i class="fa fa-trash"></i>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>           
            <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
      <!-- /Conteúdo principal -->
      <!--------------------- /Conteúdo principal ------------------------->
    </div>
  </div>

app/views/sellers/managerseller.html.erb
<div class="container-fluid">
    <div class="row">
      <!-------------------- --Conteúdo principal ------------------------->
      <!-- Conteúdo principal -->
        <div class="col-lg-9">
          <h1 class="mt-4">Gerenciamento de Vendedores</h1>
            <% if current_user.admin? %>
              <%= link_to devices_in_use_seller_path, class: 'btn btn-success' do %>
                <i class="fa fa-plus"></i> Atrelar Vendedor ao Dispositivo
              <% end %>
              <% else %>
                <div class="d-flex">
                  <%= link_to new_seller_path, class: "btn btn-success me-2" do %>
                    <i class="fa fa-user-plus"></i> Novo vendedor
                  <% end %>
                
                  <%= link_to userdevice_path, class: 'btn btn-success' do %>
                    <i class="fa fa-plus"></i> Atrelar Vendedor ao Dispositivo
                  <% end %>
                </div>
            <% end %>
          <div class="right_col" role="main">
            <!-- ... (conteúdo do gráfico e da tabela) ... -->
              <div class="container">
                <div class="row justify-content-center">
                  <div class="col-md-12">
                    <div class="table-responsive">
                      <table class="table table-responsive-sm">
                        <thead>
                          <tr>
                            <th>Status</th>
                            <th>Nome</th>
                            <th>Cartão RFID</th>
                            <th>Cargo</th>
                            <th>Doses</th>
                            <th>Email</th>
                            <th>Ver</th>
                            <th>Editar</th>
                            <th>Excluir</th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @sellers.each do |seller| %>
                            <tr>
                              <td><%= seller.status %></td>
                              <td><%= seller.nome %></td>
                              <td><%= seller.cardRFID %></td>
                              <td><button type="button" class="btn btn-info"><%= seller.cargo %></button></td>
                              <td><%= seller.contador %></td>
                              <td><%= seller.email %></td>
                              <td>
                                <%= button_to seller_path(seller), method: :get, class: 'btn btn-primary' do %>
                                  <i class="fa fa-search"></i>
                                <% end %>
                              </td>
              
                              <td>
                                <%= button_to edit_seller_path(seller), method: :get, class: 'btn btn-warning' do %>
                                  <i class="fa fa-edit"></i>
                                <% end %>
                              </td>
              
                              <td>
                                <%= button_to seller_path(seller), method: :delete, data: { confirm: 'Tem certeza que deseja excluir este usuário?' }, class: 'btn btn-danger' do %>
                                  <i class="fa fa-trash"></i>
                                <% end %>
                              </td>
                            </tr>
                          <% end %>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>           
            <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
      <!-- /Conteúdo principal -->
      <!--------------------- /Conteúdo principal ------------------------->
    </div>
  </div>

app/views/sellers/new.html.erb
<div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Cadastrar Vendedores</h1>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->
            <%= render "form", seller: @seller %>
          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>

app/views/sellers/show.html.erb
<div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Dados do Vendedor:  <%= @seller.nome %></h1>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->
            <p style="color: green"><%= notice %></p>
              <%= render @seller %>
          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>