config/routes.rb
Rails.application.routes.draw do
  get '/user_management', to: 'user_management#index', as: 'user_management'
  resources :sellers do
    member do
      post 'associate_seller', to: 'devices#associate_seller'
      
      delete 'destroy_sellers', to: 'sellers#destroy_sellers'
      #delete 'dissociate_seller', to: 'devices#dissociate_seller'
      delete 'dissociate_seller/:device_id', to: 'sellers#dissociate_seller', as: :dissociate_seller
    end
    get 'attach_devices'
    post 'save_attached_devices'
  end

  get 'home/index'
  get 'esp8266/index'
  root 'home#index'
  get '/status', to: 'status#index'
  resources :devicelogs, only: [:index]
  get 'associar_dispositivo_usuario', to: 'devices#associar_dispositivo_usuario'
  delete 'devices/:id/dissociate', to: 'devices#dissociate', as: 'dissociate_device'
  get '/devices/in_use', to: 'devices#in_use', as: 'devices_in_use'
  get '/devices/in_use_seller', to: 'devices#in_use_seller', as: 'devices_in_use_seller'
  get '/user/dashboard', to: 'user#dashboard', as: 'dashboard'
  get '/user/managerseller', to: 'sellers#managerseller', as: 'managerseller'
  get '/user/userdevice', to: 'devices#userdevice', as: 'userdevice'


  

  



  resources :dose_prices

  namespace :administrador do
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  
  resources :devices do
    post 'associate_device_seller'
    post 'assign_device', on: :member
    post 'save_to_database', on: :collection
    post 'save_data', on: :collection
    post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  end

  post 'devices/associate', to: 'devices#associate', as: 'associate_device'
  post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  resources :devices, only: [:new, :create, :show, :destroy]
  

  devise_for :users
  #devise_for :users, controllers: { registrations: 'users/registrations' }


  resources :admin, only: [:destroy]
  resources :users, only: [:index, :show, :destroy]
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      #delete '/users/cancel', to: 'users/registrations#destroy', as: :cancel_user_registration
    end


  # Rotas para o Admin
  get 'admin/index', as: 'admin_index'

  # Rotas para o User
  get 'user/index', as: 'user_index'

  # Rotas para o Envio de SMS
  

  resources :sms_messages 
    post '/send_sms_twilio', to: 'sms_messages#send_sms_twilio'
    # Rotas para o Envio de Whatsapp
    post '/send_whatsapp_message_twilio', to: 'sms_messages#send_whatsapp_message_twilio'
    get '/logs_message', to: 'sms_messages#logs_message'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/device.rb
class Device < ApplicationRecord
    #validates :device, uniqueness: true
    belongs_to :user, optional: true
    belongs_to :seller, optional: true #Dava certo é so voltar

    has_many :device_sellers
    has_many :sellers, through: :device_sellers

    #def device_name
        # Lógica para obter o nome do dispositivo
        # Por exemplo, se o nome do dispositivo estiver armazenado no campo "device" do modelo, você pode retornar assim:
        #.device
   # end

end

app/controllers/devices_controller.rb
require 'httparty'

class DevicesController < ApplicationController
    before_action :authenticate_user!
    before_action :check_admin, only: [:assign_device]
    
    def index
      response = HTTParty.get('https://dispenser-smart-api-947773b37df2.herokuapp.com/esp8266s')
      if response.code == 200
        api_data_array = JSON.parse(response.body)
    
        # Pagina os dados da API usando Kaminari
        @api_data = Kaminari.paginate_array(api_data_array).page(params[:page]).per(10)
      else
        @api_data = []
      end
    
      @users = User.all
      @devices = Device.includes(:user)
    end
      
   
    def associate
      selected_device = params[:device]
      user_id = params["user_device_#{selected_device}"]
  
      # Additional parameters from JSON data
      status = params[:status]
      ipadrrs = params[:ipadrrs]
      cont = params[:cont]
      last_seen = params[:last_seen]
      padlock = params[:padlock]
  
      # Encontra o dispositivo existente ou cria um novo
      @device = Device.find_or_create_by(device: selected_device)
  
      # Define os atributos para associar o dispositivo ao usuário
      @device.user_id = user_id
      @device.status = status
      @device.ipadrrs = ipadrrs
      @device.cont = cont
      @device.last_seen = last_seen
      @device.padlock = padlock
  
      if @device.save
        redirect_to devices_in_use_path, notice: 'Dispositivo associado com sucesso!'
      else
        redirect_to devices_path, alert: 'Erro ao associar dispositivo ao usuário.'
      end
    end
    
    
    def dissociate
      device = Device.find(params[:id])
      device.user_id = nil
      device.save
    
      redirect_to devices_path, notice: 'Associação do dispositivo removida com sucesso!'
    end

    def in_use
      @devices = Device.includes(:user).where.not(user_id: nil)
      #@devices = Device.all
    end

    def userdevice
      #@devices = Device.all # ou lógica para obter os dispositivos desejados
      # Certifique-se de que o usuário está logado
      if user_signed_in?
          # Obtenha o usuário atual
          @user = current_user
          
          # Obtenha os dispositivos atrelados a este usuário
          @devices = @user.devices
        else
          # Caso o usuário não esteja logado, você pode redirecioná-lo ou fazer outra coisa
          redirect_to new_user_session_path
        end
        @sellers = current_user.sellers
    end

    def in_use_seller
      @devices = Device.all
      @sellers = Seller.all
      #@device = Device.find(params[:id])
    end

    def associate_seller
      @device = Device.find(params[:id])
      @seller = Seller.find(params[:device][:seller_id])
  
      # Verifique se já existe uma associação para evitar duplicatas
      unless @device.sellers.include?(@seller)
        @device.sellers << @seller
      end
      redirect_to managerseller_path, notice: 'Vendedor associado com sucesso.'  
    end
  
    def dissociate_seller
      @device = Device.find(params[:device_id])
      @seller = Seller.find(params[:seller_id])
  
      if @device.sellers.exists?(@seller)
        @device.sellers.delete(@seller)
        flash[:success] = 'Vendedor desassociado com sucesso.'
      else
        flash[:error] = 'Vendedor não está associado a este dispositivo.'
      end
  
      redirect_to devices_path
    end

    def show
        @device = Device.find(params[:id])
        @devices = @user.devices if @user.present? && @user.devices.present?
    end

    private

    def device_params
      params.require(:device).permit(:device, :status, :ipadrrs, :cont, :last_seen, :padlock)
    end

    def check_admin
      redirect_to root_path, alert: 'Você não tem permissão para acessar essa página.' unless current_user.admin?
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/in_use.html.erb
<div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Dispositivos em uso</h1>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->
            <div class="table-responsive">
              <table class="table table-responsive-sm">
                <thead>
                  <tr>
                    <th>Dispositivo</th>
                    <th>Usuário</th>
                    <th></th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @devices.each do |device| %>
                    <% if device.user.present? %>
                      <tr>
                        <td><%= device.device %></td>
                        <td><%= device.user.name %></td>
                        <td>
                          <%= link_to device_path(device), class: 'btn btn-primary btn-sm' do %>
                            <i class="fa fa-search"></i> Ver
                          <% end %>
                        </td>
                        <td>
                          <%= button_to dissociate_device_path(device), method: :delete, data: { confirm: 'Tem certeza que deseja desassociar este dispositivo?' }, class: 'btn btn-danger btn-sm' do %>
                            <i class="fa fa-times"></i> Desassociar
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  <% end %>
                </tbody>
              </table>
            </div>
          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>

app/views/devices/in_use_seller.html.erb
<div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Gerenciamento do Vendedor ao Dispositivo</h1>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->
            <div class="table-responsive">
              <table class="table table-responsive-sm">
                <thead>
                  <tr>
                    <th>Dispositivo</th>
                    <th>Status</th>
                    <th>Endereço de IP</th>
                    <th>Vendedor Associado</th>
                    <th>Ação</th>
                  </tr>
                </thead>
                <tbody>
                  <% @devices.each do |device| %>
                    <tr>
                      <td><%= device.device %></td>
                      <td><%= device.status %></td>
                      <td><%= device.ipadrrs %></td>
                      <td>
                        <% if device.seller %>
                          <%= device.seller.nome %>
                        <% else %>
                          Nenhum vendedor associado
                        <% end %>
                      </td>
                      <td>
                        <% if device.seller %>
                          <%= button_to "Desassociar Vendedor", dissociate_seller_seller_path(device), method: :delete, data: { confirm: 'Tem certeza que deseja desassociar este dispositivo?' }, class: "btn btn-danger btn-sm" %>
                        <% else %>
                          <%= form_tag associate_seller_seller_path(device), method: :post, class: "d-flex" do %>
                            <%= select_tag "device[seller_id]", options_from_collection_for_select(@sellers, :id, :nome), prompt: 'Selecione um vendedor', class: 'form-control me-2' %>
                            <%= submit_tag "Associar", class: "btn btn-primary btn-sm" %>
                          <% end %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>

app/views/devices/index.html.erb
<div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Dispositivos</h1>
        <%= link_to devices_in_use_path, class: 'btn btn-primary' do %>
          <i class="fa fa-list-ul"></i> Dispositivos em Uso
        <% end %>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->
            <div class="col-md-12">
              <%= form_tag associate_device_path, method: :post do %>
                <% if @api_data.present? %>
                  <div class="table-responsive">
                    <table class="table table-responsive-sm">
                      <thead>
                        <tr>
                          <th>Nome do dispositivo</th>
                          <th>Endereço de IP</th>
                          <th>Online última vez</th>
                          <th>Associar usuário a dispositivo</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @api_data.each do |data| %>
                          <tr>
                            <td><%= data['device'] %></td>
                            <td><%= data['ipadrrs'] %></td>
                            <td><%= data['last_seen'] %></td>
                            <td>
                              <%= form_tag associate_device_path, method: :post do %>
                                <%= select_tag "user_device_#{data['device']}", options_from_collection_for_select(@users, :id, :name), prompt: 'Selecione um usuário', class: 'form-control' %>
                                <%= hidden_field_tag :device, data['device'] %>
                                <%= hidden_field_tag :status, data['status'] %>
                                <%= hidden_field_tag :ipadrrs, data['ipadrrs'] %>
                                <%= hidden_field_tag :cont, data['cont'] %>
                                <%= hidden_field_tag :last_seen, data['last_seen'] %>
                                <%= hidden_field_tag :padlock, data['padlock'] %>
                                <%= submit_tag 'Associar Usuário', class: 'btn btn-primary mt-2' %>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                <% else %>
                  <p class="text-center">Nenhum dado da API encontrado.</p>
                <% end %>
              <% end %>
              <div class="text-center">
                <%= paginate @api_data, theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center", nav_class: "d-inline-block" %>
              </div>
            </div>
          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>

app/views/devices/show.html.erb
<h1>Detalhes do Dispositivo</h1>

    <p>O dispositivo <%= @device.device %> pertence ao usuário <%= @device.user.name %></p>
    <!-- Substitua 'device' pelo atributo correto que representa o nome do dispositivo e 'user' pelo atributo correto que representa o usuário no seu modelo Device -->
    
    <%= link_to 'Voltar', devices_path %>
    

app/views/devices/show_seller.html.erb
<!-- app/views/devices/show_seller.html.erb -->

<h1>Detalhes do Dispositivo</h1>
<p>Dispositivo: <%= @device.device %></p>
<p>Status: <%= @device.status %></p>
<p>Endereço de IP: <%= @device.ipadrrs %></p>

<% if @device.seller %>
  <p>Vendedor Associado: <%= @device.seller.nome %></p>
  <%= button_to "Desassociar Vendedor", dissociate_seller_seller_path(@device), method: :delete, data: { confirm: 'Tem certeza que deseja desassociar este dispositivo?' }, class: "btn btn-danger" %>
<% else %>
  <p>Nenhum vendedor associado.</p>
<% end %>

app/views/devices/userdevice.html.erb
<!-- app/views/devices/index.html.erb -->

<h1>Lista de Dispositivos</h1>
<% @devices.each do |device| %>
    <% if device.sellers.present? %>
    <table class="table">
        <thead>
        <tr>
            <th>Vendedor</th>
            <th>Ação</th>
        </tr>
        </thead>
        <tbody>
        <% device.sellers.each do |seller| %>
            <tr>
            <td><%= seller.nome %></td>
            <td>
                <%= button_to "Desassociar", dissociate_seller_seller_path(device, seller), method: :delete, data: { confirm: 'Tem certeza que deseja desassociar este vendedor?' }, class: "btn btn-danger btn-sm" %>
            </td>
            </tr>
        <% end %>
        </tbody>
    </table>
    <% else %>
    Nenhum vendedor associado a este dispositivo.
    <% end %>
<% end %>




  <div class="container-fluid">
  <div class="row">
    <!-------------------- --Conteúdo principal ------------------------->
    <!-- Conteúdo principal -->
      <div class="col-lg-9">
        <h1 class="mt-4">Gerenciamento do Vendedor ao Dispositivo</h1>
        <div class="right_col" role="main">
          <!-- ... (conteúdo do gráfico e da tabela) ... -->
            <div class="table-responsive">
              <table class="table table-responsive-sm">
                <thead>
                  <tr>
                    <th>Dispositivo</th>
                    <th>Status</th>
                    <th>Endereço de IP</th>
                    <th>Vendedor Associado</th>
                    <th>Ação</th>
                  </tr>
                </thead>
                <tbody>
                  <% @devices.each do |device| %>
                    <tr>
                      <td><%= device.device %></td>
                      <td><%= device.status %></td>
                      <td><%= device.ipadrrs %></td>
                      <td>
                        <% if device.seller %>
                          <%= device.seller.nome %>
                        <% else %>
                          Nenhum vendedor associado
                        <% end %>
                      </td>
                      <td>
                        <% if device.seller %>
                          <%= button_to "Desassociar Vendedor", dissociate_seller_seller_path(device), method: :delete, data: { confirm: 'Tem certeza que deseja desassociar este dispositivo?' }, class: "btn btn-danger btn-sm" %>
                        <% else %>
                          <%= form_tag associate_seller_seller_path(device), method: :post, class: "d-flex" do %>
                            <%= select_tag "device[seller_id]", options_from_collection_for_select(@sellers, :id, :nome), prompt: 'Selecione um vendedor', class: 'form-control me-2' %>
                            <%= submit_tag "Associar", class: "btn btn-primary btn-sm" %>
                          <% end %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          <!-- ... (Fnal conteúdo do gráfico e da tabela) ... -->  
    <!-- /Conteúdo principal -->
    <!--------------------- /Conteúdo principal ------------------------->
  </div>
</div>