config/routes.rb
Rails.application.routes.draw do
  get '/user_management', to: 'user_management#index', as: 'user_management'
  resources :sellers do
    member do
      post 'associate_seller', to: 'devices#associate_seller'
      
      delete 'destroy_sellers', to: 'sellers#destroy_sellers'
      #delete 'dissociate_seller', to: 'devices#dissociate_seller'
      delete 'dissociate_seller/:device_id', to: 'sellers#dissociate_seller', as: :dissociate_seller
    end
    get 'attach_devices'
    post 'save_attached_devices'
  end

  get 'home/index'
  get 'esp8266/index'
  root 'home#index'
  get '/status', to: 'status#index'
  resources :devicelogs, only: [:index]
  get 'associar_dispositivo_usuario', to: 'devices#associar_dispositivo_usuario'
  delete 'devices/:id/dissociate', to: 'devices#dissociate', as: 'dissociate_device'
  get '/devices/in_use', to: 'devices#in_use', as: 'devices_in_use'
  get '/devices/in_use_seller', to: 'devices#in_use_seller', as: 'devices_in_use_seller'
  get '/user/dashboard', to: 'user#dashboard', as: 'dashboard'
  get '/user/managerseller', to: 'sellers#managerseller', as: 'managerseller'
  get '/user/userdevice', to: 'devices#userdevice', as: 'userdevice'


  

  



  resources :dose_prices

  namespace :administrador do
    resources :users, only: [:index, :edit, :update, :destroy]
  end
  
  resources :devices do
    post 'associate_device_seller'
    post 'assign_device', on: :member
    post 'save_to_database', on: :collection
    post 'save_data', on: :collection
    post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  end

  post 'devices/associate', to: 'devices#associate', as: 'associate_device'
  post 'devices/fetch_and_save_data', to: 'devices#fetch_and_save_data', as: 'fetch_and_save_data_devices'
  resources :devices, only: [:new, :create, :show, :destroy]
  

  devise_for :users
  #devise_for :users, controllers: { registrations: 'users/registrations' }


  resources :admin, only: [:destroy]
  resources :users, only: [:index, :show, :destroy]
    devise_scope :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      #delete '/users/cancel', to: 'users/registrations#destroy', as: :cancel_user_registration
    end


  # Rotas para o Admin
  get 'admin/index', as: 'admin_index'

  # Rotas para o User
  get 'user/index', as: 'user_index'

  # Rotas para o Envio de SMS
  

  resources :sms_messages 
    post '/send_sms_twilio', to: 'sms_messages#send_sms_twilio'
    # Rotas para o Envio de Whatsapp
    post '/send_whatsapp_message_twilio', to: 'sms_messages#send_whatsapp_message_twilio'
    get '/logs_message', to: 'sms_messages#logs_message'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device.rb
class Device < ApplicationRecord
    #validates :device, uniqueness: true
    belongs_to :user, optional: true
    belongs_to :seller, optional: true #Dava certo é so voltar

    has_many :device_sellers
    has_many :sellers, through: :device_sellers

    #def device_name
        # Lógica para obter o nome do dispositivo
        # Por exemplo, se o nome do dispositivo estiver armazenado no campo "device" do modelo, você pode retornar assim:
        #.device
   # end

end

app/models/device_seller.rb
class DeviceSeller < ApplicationRecord
  belongs_to :device
  belongs_to :seller
end

app/models/dose_price.rb
class DosePrice < ApplicationRecord
    validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/seller.rb
class Seller < ApplicationRecord
    #has_and_belongs_to_many :devices #funciona basta voltar
    has_many :device_sellers
    has_many :devices, through: :device_sellers
end

app/models/sms_log.rb
class SmsLog < ApplicationRecord
   
end

app/models/sms_message.rb
class SmsMessage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :devices
  has_one :sms_configuration
  has_many :sellers, foreign_key: "creator_id"


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         enum role: { admin: 'admin', user: 'user'}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def index
        @devices = current_user.devices
    end

    def dashboard
        # Obter os dados da API
        response = HTTParty.get('https://dispenser-smart-api-947773b37df2.herokuapp.com/esp8266s')
        data = JSON.parse(response.body)
      
        # Obter a quantidade total de IDs
      
        # Preparar os dados para o gráfico
        total_ids = data.count
        chart_data = data.map { |entry| [entry['created_at'], entry['cont']] }
        @total_ids = total_ids
        @chart_data_json = chart_data.to_json
      
      
        @devices = Device.all
        if @devices.any?
            @device_names = @devices.pluck(:device)
            @device_counts = @devices.pluck(:cont)
        else
            # Lida com a situação em que não há registros
            # Por exemplo, você pode definir valores padrão ou exibir uma mensagem
        end

        #VENDEDORES
        @user = current_user  # Suponha que você tenha o método current_user definido para obter o usuário atual
        @sellers = @user.sellers  # Isso buscará todos os vendedores associados ao usuário atual
        @sellers_count = @sellers.count
      
        @user = current_user  # Suponha que você tenha o método current_user definido para obter o usuário atual
        @devices = @user.devices  # Isso buscará todos os vendedores associados ao usuário atual
        @devices_count = @devices.count

        @seller_sales = Seller.group(:nome).sum(:contador)
        @seller_names = @seller_sales.keys
        @total_sales = @seller_sales.values
      
        @users = User.all
        @role_counts = @users.group(:role).count
      
        @users = User.where(role: 'user')
        @users_total = @users.count
      
        dose_price = DosePrice.first.price
        total_doses = data.sum { |entry| entry['cont'] }
      
        @total_price = total_doses * dose_price
        @results = data
    end
  
    def show
        @user = User.find(params[:id])
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_manager_helper.rb
module ApiManagerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devicelogs_helper.rb
module DevicelogsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/dose_prices_helper.rb
module DosePricesHelper
end

app/helpers/esp8266_helper.rb
module Esp8266Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<body class="d-flex flex-column min-vh-100">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to admin_index_path, class: 'navbar-brand' do %>
      <i class="fa fa-home"></i>
      Painel Administrativo
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
            Opções <i class="fa fa-gear"></i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">
              <i class="fa fa-user"></i>
              <%= current_user.name %>
            </a>                
            <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
              <i class="fa fa-cog"></i>
              Editar
            <% end %>                
            <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
              <i class="fa fa-sign-out"></i>
              Sair
            <% end %>              
          </div> 
        </li>
      </ul>
    </div>
  </nav>


  <div class="d-flex flex-grow-1">
    <aside class="col-md-3 col-lg-2 bg-dark p-0">
      <!-- Seu código de Sidebar aqui -->
      <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
          <i class="fa fa-bars me-2" aria-hidden="true"></i>
          <span class="fs-4">Menu</span>
        </a>
        <hr>
          <ul class="nav nav-pills flex-column mb-auto">
            <% if current_user.role == "admin" %>
              <!-- Código para administradores -->
              <li class="nav-item">
                <%= link_to admin_index_path, class: "nav-link active", "aria-current" => "page" do %>
                  <i class="fa fa-home me-2" aria-hidden="true"></i>
                  Home
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to administrador_users_path, class: "nav-link text-white d-flex align-items-center" do %>
                  <i class="fa fa-user me-2" aria-hidden="true"></i>
                  Gestão de Usuários
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to sellers_path, class: "nav-link text-white d-flex align-items-center" do %>
                  <i class="fa fa-users me-2" aria-hidden="true"></i>
                  Gestão de Vendedores
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to status_path, class: "nav-link text-white d-flex align-items-center" do %>
                  <i class="fa fa-desktop me-2" aria-hidden="true"></i>
                  Meus Dispositivos
                <% end %>
              </li>


              <li class="nav-item">
                <%= link_to devices_path, class: "nav-link text-white d-flex align-items-center" do %>
                  <i class="fa fa-cogs me-2" aria-hidden="true"></i>
                  Gestão de Dispositivos
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to sms_messages_path, class: "nav-link text-white d-flex align-items-center" do %>
                  <i class="fa fa-envelope me-2" aria-hidden="true"></i>
                  Painel de Mensagens
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to dose_prices_path, class: "nav-link text-white d-flex align-items-center" do %>
                  <i class="fa fa-dollar me-2" aria-hidden="true"></i>
                  Configuração de Preço
                <% end %>
              </li>
              <% else %>
              <!-- Código para usuários normais -->
              <li class="nav-item">
                <%= link_to admin_index_path, class: "nav-link active", "aria-current" => "page" do %>
                  <i class="fa fa-home me-2" aria-hidden="true"></i>
                  Home
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to sellers_path, class: "nav-link text-white d-flex align-items-center" do %>
                  <i class="fa fa-users me-2" aria-hidden="true"></i>
                  Gestão de Vendedores
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to status_path, class: "nav-link text-white d-flex align-items-center" do %>
                  <i class="fa fa-desktop me-2" aria-hidden="true"></i>
                  Meus Dispositivos
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to dose_prices_path, class: "nav-link text-white d-flex align-items-center" do %>
                  <i class="fa-regular fa-money-bills-simple"></i>
                  Configuração de Preço
                <% end %>
              </li>
            <% end %>
          </ul>
        </hr>
      </div>
    </aside>
    <main class="col">
      <!-- Seu conteúdo principal aqui -->
    </main>
  </div>
</body>